# Add configuration values here, as shown below.
#
email_platform: 'sipastos@gmail.com'
password_email: 'pastos2017'
url_app: 'http://localhost:3000'
app_id_facebook: '1447536465359074'
app_secret_facebook: '4b41e6307b12fd503a4149c45edccaa6'
callback_facebok: '/users/auth/facebook/callback'

#
production:
  url_app: 'http://si-pastosunal.herokuapp.com/'
  app_id_facebook: '1447536465359074'
  app_secret_facebook: '4b41e6307b12fd503a4149c45edccaa6'
  callback_facebok: '/users/auth/facebook/callback'
  email_platform: 'sipastos@gmail.com'
  password_email: 'pastos2017'
