# Add configuration values here, as shown below.
#

SECRET_KEY_BASE: dfkgjdfklgjfdlkjgdklf
S3_KEY: 'AKIAIUCBEGM4GCBDZWOQ'
S3_SECRET: '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'
S3_BUCKET: 'images-ingesoft'
S3_REGION: 'sa-east-1'

USER_SEND_GRID: 'jhont285'
PASSWORD_SEND_GRID: 'unal2013'
GMAIL_ADDRESS: 'smtp.gmail.com'
GMAIL_DOMAIN: 'gmail.com'
GMAIL_EMAIL: 'sipastos@gmail.com'
GMAIL_PASSWORD: 'pastos2017'
URL_APP: 'http://localhost:3000'
FACEBOOK_APP_ID: '355766128209717'
FACEBOOK_APP_SECRET: 'c84457fb15f73617dbd8d7d76f4713e0'
GOOGLE_APP_ID:  '931350528514-85tegk50os3f8mdqvmmen86p5sb8c479.apps.googleusercontent.com'
GOOGLE_APP_SECRET: 'WuYmb2gwVEUhr4_VHzTMyPzb'
TWITTER_APP_ID: 'P0MDXNLJh0grOT5yGJj07zd8N'
TWITTER_APP_SECRET: 'WunQa1WTN9zDnHD8ewwsxYrluPJVynyH84pplutmVCA81QGQsH'


production:
  URL_APP: 'https://sipastosensayo.herokuapp.com'

  FACEBOOK_APP_ID: '1447536465359074'
  FACEBOOK_APP_SECRET: '4b41e6307b12fd503a4149c45edccaa6'
  GOOGLE_APP_ID:  '931350528514-eud7677gi5hq13gujeqpk6soo6j7ckg5.apps.googleusercontent.com'
  GOOGLE_APP_SECRET: 'ZnTHnj9LzaipMUqYFDAO-yxO'
  TWITTER_APP_ID: 'FcZ14HznnXwUl4Juvho9u1gBF'
  TWITTER_APP_SECRET: 'E59lcsz0Vx7OMfslUJ7qGEM7lOHpdWrsWq0ss1bwLtmSNgtWBx'
