# Add configuration values here, as shown below.
#

S3_KEY: 'AKIAJOAVT7UEQOI735VA'
S3_SECRET: '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'
S3_BUCKET: 'images-ingesoft'
S3_REGION: 'sa-east-1'
email_platform: 'sipastos@gmail.com'
password_email: 'pastos2017'
url_app: 'http://localhost:3000'
FACEBOOK_APP_ID: '355766128209717'
FACEBOOK_APP_SECRET: 'c84457fb15f73617dbd8d7d76f4713e0'
GOOGLE_APP_ID:  '931350528514-85tegk50os3f8mdqvmmen86p5sb8c479.apps.googleusercontent.com'
GOOGLE_APP_SECRET: 'WuYmb2gwVEUhr4_VHzTMyPzb'
GMAIL_DOMAIN: 'gmail.com'
TWITTER_APP_ID: 'P0MDXNLJh0grOT5yGJj07zd8N'
TWITTER_APP_SECRET: 'WunQa1WTN9zDnHD8ewwsxYrluPJVynyH84pplutmVCA81QGQsH'


production:
  email_platform: 'sipastos@gmail.com'
  password_email: 'pastos2017'
  url_app: 'https://sipastosensayo.herokuapp.com'

  FACEBOOK_APP_ID: '1447536465359074'
  FACEBOOK_APP_SECRET: '4b41e6307b12fd503a4149c45edccaa6'
  GOOGLE_APP_ID:  '931350528514-eud7677gi5hq13gujeqpk6soo6j7ckg5.apps.googleusercontent.com'
  GOOGLE_APP_SECRET: 'ZnTHnj9LzaipMUqYFDAO-yxO'
  TWITTER_APP_ID: 'FcZ14HznnXwUl4Juvho9u1gBF'
  TWITTER_APP_SECRET: 'E59lcsz0Vx7OMfslUJ7qGEM7lOHpdWrsWq0ss1bwLtmSNgtWBx'
